name: pipeline

on:
  push:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        run: org.sonarsource.scanner.maven:sonar
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
        aws-region: us-east-1
#    - name: Update aws access key
#      run: sed -i 's/<aws_access_key>/${{ secrets.AWS_ACCESS_KEY_ID_ORG }}/g' src/main/resources/application.properties
#
#    - name: Update aws access secret
#      run: sed -i 's/<aws_access_secret>/${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}/g' src/main/resources/application.properties
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.2'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: postech-repository
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Update Kube File
      run: aws eks update-kubeconfig --name g35-eks-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml



